import { SYSTEM_RULES } from "./system-rules";

/**
 * The system prompt, in two blocks.
 *
 * The split is deliberate. Both halves are byte-identical on every request, so
 * the cache breakpoint goes at the end of the second block: the first turn of a
 * conversation writes ~3,300 tokens of prefix to cache, and every turn after it
 * re-reads that prefix at cache rates instead of full input rates. Only the
 * conversation itself is billed as fresh input.
 *
 * The design work this required was simply keeping the variable part (the
 * conversation) after the fixed part. Put anything per-request in here — a
 * timestamp, the visitor's page — and the cache never hits.
 *
 * Both halves are generated by tools/build_kb.py: the rules from
 * chatbot/system-rules.md, the knowledge base from the website's own HTML.
 * Neither can drift from what the business approved or what the site says.
 */
export function buildSystem(knowledgeBase: string) {
  return [
    { type: "text" as const, text: SYSTEM_RULES },
    {
      type: "text" as const,
      text:
        "# KNOWLEDGE BASE\n\nEverything you are allowed to state as fact:\n\n" +
        knowledgeBase,
      cache_control: { type: "ephemeral" as const },
    },
  ];
}
